spring: 
  profiles: 
    active: 
      - dev
---
spring:
  profiles: dev # 开发环境
    active: 
      application: 
      name: USER-DEV
---
spring: 
  profiles: test # 测试环境
    active: 
      application: 
      name: USER-TEST